import { NextRequest, NextResponse } from 'next/server'
import { createRouteHandlerClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import { supabaseAdmin } from '@/lib/supabase-admin'

// ─── GET /api/projects ────────────────────────────────────────────────────────
// Returns all projects for the logged-in user.
export async function GET() {
  const supabase = createRouteHandlerClient({ cookies })
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: projects, error } = await supabaseAdmin
    .from('projects')
    .select(`
      id, name, domain, api_key, created_at,
      campaigns ( settings ),
      events ( count )
    `)
    .eq('user_id', user.id)
    .order('created_at', { ascending: false })

  if (error) return NextResponse.json({ error: 'Failed to fetch projects' }, { status: 500 })

  return NextResponse.json({ projects })
}

// ─── POST /api/projects ───────────────────────────────────────────────────────
// Creates a new project and default campaign settings.
export async function POST(req: NextRequest) {
  const supabase = createRouteHandlerClient({ cookies })
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { name, domain } = await req.json()

  if (!name?.trim()) {
    return NextResponse.json({ error: 'Project name is required' }, { status: 400 })
  }

  // Create the project (api_key is auto-generated by DB default)
  const { data: project, error } = await supabaseAdmin
    .from('projects')
    .insert({
      user_id: user.id,
      name: name.trim(),
      domain: domain?.trim() || null,
    })
    .select()
    .single()

  if (error) return NextResponse.json({ error: 'Failed to create project' }, { status: 500 })

  // Create default widget settings for this project
  await supabaseAdmin.from('campaigns').insert({ project_id: project.id })

  return NextResponse.json({ project }, { status: 201 })
}

