import { NextRequest, NextResponse } from 'next/server'
import { createRouteHandlerClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import { supabaseAdmin } from '@/lib/supabase-admin'

// ─── GET /api/projects ────────────────────────────────────────────────────────
// Returns all projects for the logged-in user.
export async function GET() {
  const supabase = createRouteHandlerClient({ cookies })
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: projects, error } = await supabaseAdmin
    .from('projects')
    .select(`
      id, name, domain, api_key, created_at,
      campaigns ( settings ),
      events ( count )
    `)
    .eq('user_id', user.id)
    .order('created_at', { ascending: false })

  if (error) return NextResponse.json({ error: 'Failed to fetch projects' }, { status: 500 })

  return NextResponse.json({ projects })
}

// ─── POST /api/projects ───────────────────────────────────────────────────────
// Creates a new project and default campaign settings.
export async function POST(req: NextRequest) {
  const supabase = createRouteHandlerClient({ cookies })
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { name, domain } = await req.json()

  if (!name?.trim()) {
    return NextResponse.json({ error: 'Project name is required' }, { status: 400 })
  }

  // Create the project (api_key is auto-generated by DB default)
  const { data: project, error } = await supabaseAdmin
    .from('projects')
    .insert({
      user_id: user.id,
      name: name.trim(),
      domain: domain?.trim() || null,
    })
    .select()
    .single()

  if (error) return NextResponse.json({ error: 'Failed to create project' }, { status: 500 })

  // Create default widget settings for this project
  await supabaseAdmin.from('campaigns').insert({ project_id: project.id })

  // Seed default (disabled) growth configs — wrapped in try/catch so project
  // creation still succeeds if the social_proof_growth table hasn't been
  // migrated yet (e.g. during initial setup).
  try {
    const growthDefaults = [
      { type: 'purchases', start_value: 55,  end_value: 159, message_template: '{count} people bought this week' },
      { type: 'signups',   start_value: 12,  end_value: 45,  message_template: '{count} people joined this week' },
      { type: 'visitors',  start_value: 18,  end_value: 72,  message_template: '{count} people visited this week' },
    ]
    await supabaseAdmin.from('social_proof_growth').insert(
      growthDefaults.map((g) => ({
        user_id: user.id,
        project_id: project.id,
        ...g,
        current_value: g.start_value,
        current_day: 0,
        enabled: false,
      })),
    )
  } catch (growthErr) {
    // Non-fatal: growth table may not exist yet. Run the migration first.
    console.warn('[POST /api/projects] Could not seed growth configs:', growthErr)
  }

  return NextResponse.json({ project }, { status: 201 })
}
